language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install pip --upgrade
  - pip install setuptools --upgrade
  - pip install -r requirements/prod.txt
  - pip install pytest-django==3.6.0
# command to run tests
script:
  - pytest