language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install pip --upgrade
  - pip install setuptools --upgrade
  - pip install -r requirements/dev.txt
  - pip install pytest-django==3.6.0
# command to run tests
script:
  - pytest
  - coverage run --source=tugcan,panel,blog --omit=tugcan/runner.py,tugcan/middleware.py -m pytest
  - flake8
after_success:
  - coverage report -m
