# Generated by Django 2.1.4 on 2019-01-08 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("panel", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="date created"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentTags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="panel.Content"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="date created"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contenttags",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.Tags"
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="panel.Categories",
            ),
        ),
    ]
