# Generated by Django 2.1.4 on 2019-02-22 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='static',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
        ),
    ]
